# Generated by Django 3.1.3 on 2020-12-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, unique=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Color', models.CharField(choices=[('r', 'czerwone'), ('w', 'białe'), ('p', 'różowe')], max_length=1)),
                ('taste', models.CharField(choices=[('s', 'slodkie'), ('se', 'polslodkie'), ('d', 'wytrawne'), ('sd', 'połwytrawne')], max_length=2)),
                ('descriptions', models.TextField(blank=True, default='', verbose_name='opis')),
                ('picture', models.TextField(blank=True, default='', verbose_name='picture')),
            ],
        ),
    ]
