# Generated by Django 3.1.3 on 2021-01-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wines',
            name='color',
            field=models.CharField(choices=[('r', 'czerwone'), ('w', 'białe'), ('p', 'różowe')], max_length=1, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='taste',
            field=models.CharField(choices=[('s', 'słodkie'), ('se', 'półsłodkie'), ('d', 'wytrawne'), ('sd', 'półwytrawne')], max_length=2, verbose_name='taste'),
        ),
    ]
