# Generated by Django 3.1.2 on 2020-12-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wines',
            old_name='Color',
            new_name='color',
        ),
    ]
