# Generated by Django 3.1.3 on 2021-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210131_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='pictures',
            field=models.ImageField(upload_to='Wystawowe/'),
        ),
    ]
