# Generated by Django 3.1.3 on 2021-01-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210109_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.TextField(max_length=32, verbose_name='nickName')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
            ],
        ),
    ]
