# Generated by Django 3.1.3 on 2021-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210131_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wineimage',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opinia'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=32, null=True, verbose_name='Imię'),
        ),
    ]
