# Generated by Django 3.1.3 on 2021-01-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210127_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='index.wine'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=32, null=True, verbose_name='nickname'),
        ),
    ]
