# Generated by Django 3.1.3 on 2021-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210110_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='wines',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
