# Generated by Django 3.1.3 on 2021-02-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210201_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wineimage',
            options={},
        ),
    ]
