# Generated by Django 3.1.3 on 2021-01-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210127_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='index.wine'),
        ),
    ]
