# Generated by Django 3.1.3 on 2021-01-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_wines_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wines',
            name='comments',
        ),
    ]
