# Generated by Django 3.1.3 on 2021-01-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210127_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Wine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='index.wine'),
            preserve_default=False,
        ),
    ]
