# Generated by Django 3.1.3 on 2021-01-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_wines_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wines',
            name='picture',
        ),
    ]
