# Generated by Django 3.1.3 on 2021-01-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_comments_winefk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='WineFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='index.wines'),
        ),
    ]
