# Generated by Django 3.1.3 on 2021-01-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20210119_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
