# Generated by Django 3.1.3 on 2021-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20210119_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='WineFK',
            new_name='Wine',
        ),
        migrations.AlterField(
            model_name='comments',
            name='nickname',
            field=models.CharField(max_length=32, verbose_name='nickname'),
        ),
    ]
